<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Postivo\Models\Components;


/** GroupResponse - Address Book group details returned by the API. */
class GroupResponse
{
    /**
     * Group name.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Unique system-assigned group ID.
     *
     * @var int $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public int $id;

    /**
     * Optional group description.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * @param  string  $name
     * @param  int  $id
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(string $name, int $id, ?string $description = null)
    {
        $this->name = $name;
        $this->id = $id;
        $this->description = $description;
    }
}