<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Postivo\Models\Components;


/** RecipientFromAddressBookByExternalId - Select shipment recipient data from the Address Book by external (custom) ID. */
class RecipientFromAddressBookByExternalId
{
    /**
     * External (custom) ID of the recipient stored in your Address Book.
     *
     * @var string $extId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ext_id')]
    public string $extId;

    /**
     * Optional postscript printed above the recipient data on the envelope.
     *
     * @var ?string $postscript
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postscript')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postscript = null;

    /**
     * Set to true to fetch recipient data by external ID from a main account’s shared Address Book.
     *
     * @var ?bool $fromShared
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_shared')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $fromShared = null;

    /**
     * Custom shipment ID assigned by the user.
     *
     * @var ?string $customId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customId = null;

    /**
     * @param  string  $extId
     * @param  ?bool  $fromShared
     * @param  ?string  $customId
     * @param  ?string  $postscript
     * @phpstan-pure
     */
    public function __construct(string $extId, ?string $postscript = null, ?bool $fromShared = false, ?string $customId = null)
    {
        $this->extId = $extId;
        $this->postscript = $postscript;
        $this->fromShared = $fromShared;
        $this->customId = $customId;
    }
}